services:
  php:
    build:
      context: docker
      dockerfile: ./Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel
    depends_on:
      - db
    command: php-fpm

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    volumes:
      - ./src:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
